steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'api/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'create-env']
  env:
    - 'MONGODB_URL=${_MONGODB_URL}'
    - 'SERVICE_URL=${_SERVICE_URL}'
    - 'SECRET=${_SECRET}'
    - 'DEV_PORT=${_DEV_PORT}'
    - 'SQUARE_ACCESS_TOKEN=${_SQUARE_ACCESS_TOKEN}'
  dir: 'api/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'api/'
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', 'api.yaml', '-v', '$_GAE_VERSION']
  dir: 'api/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'client'
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "create-env"]
  env:
    - 'REACT_APP_SERVICE_URL=${_REACT_APP_SERVICE_URL}'
    - 'REACT_APP_BACKEND_URL=${_REACT_APP_BACKEND_URL}'
    - 'REACT_APP_GRAPHQL_URL=${_REACT_APP_GRAPHQL_URL}'
    - 'REACT_APP_GRAPHQL_WS_URL=${_REACT_APP_GRAPHQL_WS_URL}'
  dir: 'client/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'client'
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', 'client.yaml', '-v', '$_GAE_VERSION']
  dir: 'client'
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', 'dispatch.yaml', '-v', '$_GAE_VERSION']
  dir: 'client/'
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'services', '--project', $PROJECT_ID', 'set-traffic', '--splits', '$_GAE_TRAFFIC']
timeout: "1600s"