version: "3.9"

services:
  backend:
    image: riceapps/hedwig-api:latest

    restart: unless-stopped

    env_file:
      - ./env

    volumes:
      - $PWD/firebase.json:/firebase.json

    networks:
      - app-network

  redis:
    image: redis:alpine

    container_name: redis

    restart: unless-stopped

    user: redis

    command: redis-server

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - app-network

  frontend:
    image: riceapps/hedwig-client:latest

    container_name: frontend

    restart: unless-stopped

    ports:
      - 80:80
      - 443:443

    volumes:
      - web-root:/var/www/html
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs

    depends_on:
      - backend
      - redis

    networks:
      - app-network

  certbot:
    image: certbot/certbot

    container_name: certbot

    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html

    depends_on:
      - frontend

    command: certonly --webroot --webroot-path=/var/www/html --email team.riceapps@gmail.com --agree-tos --no-eff-email --force-renewal -d hedwig.riceapps.site

  watchtower:
    image: containrrr/watchtower

    container_name: watchtower

    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/harry/.docker/config.json:/config.json

    command: --interval 300

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/harry/Hedwig/dhparam
      o: bind

networks:
  app-network:
    driver: bridge
