services:
  api:
    build: ./api
    ports:
      - "3001:3001"
  client:
    build: ./client
    ports:
      - "3000:3000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
