# This is a basic workflow to help you get started with Actions

name: Hedwig Staging Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dockerized ]
  pull_request:
    branches: [ dockerized ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  api-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Files
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile 
          push: true
          tags: riceapps/hedwig-api:latest

  client-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v2
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile 
          push: true
          tags: riceapps/hedwig-client:latest 

          
          
#   deploy:
#     needs: build
    
#     runs-on: ubuntu-latest
    
#     steps: 
#       - name: Checkout files
#         uses: actions/checkout@v2
        
#       - name: Install doctl
#         uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

#       - name: Delete previous droplet
#         run: y | doctl compute droplet delete "staging" || true

#       - name: Provision Droplet
#         run: doctl compute droplet create "staging" --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --wait
    
#       - name: Setup Droplet with container
#         run: doctl compute ssh "staging" --ssh-command "docker run -d -p 3001:3001 --name api riceapps/hedwigunified:latest"
          
